/**
 * Describe the record, never the motive.
 *
 * Edit-with-reason is the one place on this path where a person types free text
 * that will be published under the project's name. Every other published
 * sentence is generated by a rule that was written once and reviewed; this one
 * is written at the moment of deciding, by someone who has just read the
 * evidence and formed a view. That is exactly when the invariant is easiest to
 * breach, so it is enforced here rather than trusted.
 *
 * **The lexicon is narrower than P7's**, deliberately. The records-request
 * letter forbids "delay", "overdue" and "late" because a *request* that used
 * them would be an accusation dressed as a form. A *finding* may say minutes
 * were not published ninety days after a meeting — that is the record, stated
 * as arithmetic, and forbidding the vocabulary of elapsed time would forbid the
 * findings this project exists to publish. What is forbidden here is the
 * assertion of intent, corruption or illegality: the claim that someone meant
 * it, profited by it, or broke a law doing it.
 *
 * Matching is word-bounded for the same reason P7's is: "late" must not match
 * "related", or the guard would be forbidding English rather than accusation.
 */

export const MOTIVE_TERMS: readonly string[] = [
  "bribe",
  "bribery",
  "kickback",
  "kickbacks",
  "corrupt",
  "corruption",
  "fraud",
  "fraudulent",
  "embezzle",
  "embezzlement",
  "graft",
  "collusion",
  "collude",
  "colluded",
  "conspire",
  "conspired",
  "conspiracy",
  "criminal",
  "illegal",
  "illegally",
  "unlawful",
  "unlawfully",
  "crime",
  "felony",
  "cover-up",
  "coverup",
  "conceal",
  "concealed",
  "cover up",
  "deliberate",
  "deliberately",
  "intentional",
  "intentionally",
  "knowingly",
  "wilful",
  "willful",
  "wilfully",
  "willfully",
  "wrongdoing",
  "misconduct",
  "malfeasance",
  "self-dealing",
  "self dealing",
  "bad faith",
  "rigged",
  "rigging",
  "payoff",
  "payoffs",
  "sham",
  "scheme to",
  "in order to benefit",
  "obstruct",
  "obstructed",
  "stonewall",
  "stonewalled",
];

function wordBounded(term: string): RegExp {
  return new RegExp(`\\b${term.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`, "i");
}

/**
 * The motive terms present in `text`, in lexicon order. Empty means clean.
 *
 * Returns the matches rather than a boolean so the refusal can name what it
 * objected to — an operator told only "rejected" edits blindly until something
 * passes, which is how a guard becomes a puzzle.
 */
export function motiveTerms(text: string): string[] {
  return MOTIVE_TERMS.filter((term) => wordBounded(term).test(text));
}

export function assertsMotive(text: string): boolean {
  return motiveTerms(text).length > 0;
}
