import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { PressroomCard } from "@/components/PressroomUI";
import type { DisputeItem, DisputeListing, DisputeStatus } from "@/types";

/**
 * The disputes half of `/admin/review`.
 *
 * Same screen as the findings queue, deliberately — an operator should have one
 * place they review things, and the project one place it records what was
 * decided. What is *not* shared is the treatment, because the two are different
 * objects and confusing them is the failure mode:
 *
 * A **finding** is a claim this project makes. It is generated by a detector,
 * it cites stored artifacts, and approving it publishes it. A **dispute** is a
 * stranger's contest of a record. It cites nothing, it is never published, and
 * upholding it publishes nothing and changes nothing — it is a decision to look
 * again, after which correcting the record is a separate act with its own
 * reason. So there is no approve button here and no citation panel, and the
 * card says in words what upholding does, because an operator who reads
 * "approve" on both screens will eventually treat them as the same act.
 *
 * The contester's own words are rendered as text and nowhere else. They are not
 * summarised, because a generated summary of a dispute would be this project
 * putting words in the mouth of someone contesting it.
 */

const focusRing =
  "focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent";

const buttonClass =
  "border border-ink bg-ink px-4 py-2 text-[11px] font-semibold uppercase tracking-label text-paper hover:bg-ink-soft disabled:opacity-50";

const secondaryButtonClass =
  "border border-rule px-4 py-2 text-[11px] font-semibold uppercase tracking-label text-muted hover:border-ink hover:text-ink disabled:opacity-50";

const fieldClass =
  "mt-1.5 block w-full border border-rule bg-paper px-3 py-2 text-sm text-ink hover:border-ink";

const STATUSES: readonly DisputeStatus[] = ["received", "upheld", "declined"];

const STATUS_LABEL: Record<DisputeStatus, string> = {
  received: "Awaiting review",
  upheld: "Upheld",
  declined: "Declined",
};

const EMPTY_LABEL: Record<DisputeStatus, string> = {
  received: "No dispute is waiting for review.",
  upheld: "No dispute has been upheld.",
  declined: "No dispute has been declined.",
};

function formatStamp(value: string | null): string {
  if (!value) return "—";
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? value : date.toLocaleString();
}

type LoadResult = { ok: true; body: DisputeListing } | { ok: false };

export function DisputeQueue() {
  const [status, setStatus] = useState<DisputeStatus>("received");
  const [listing, setListing] = useState<DisputeListing | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [busy, setBusy] = useState("");
  const [reasonById, setReasonById] = useState<Record<string, string>>({});

  const fetchDisputes = useCallback(async (): Promise<LoadResult> => {
    try {
      const res = await fetch(`/api/admin/review/disputes?status=${status}`, {
        credentials: "same-origin",
      });
      if (!res.ok) return { ok: false };
      return { ok: true, body: (await res.json()) as DisputeListing };
    } catch {
      return { ok: false };
    }
  }, [status]);

  const applyResult = useCallback((result: LoadResult) => {
    if (result.ok) {
      setListing(result.body);
      setError("");
    } else {
      setError("The disputes could not be loaded.");
    }
    setLoading(false);
  }, []);

  useEffect(() => {
    let ignore = false;
    void (async () => {
      const result = await fetchDisputes();
      if (ignore) return;
      applyResult(result);
    })();
    return () => {
      ignore = true;
    };
  }, [applyResult, fetchDisputes]);

  async function decide(item: DisputeItem, decision: "uphold" | "decline") {
    const id = item.dispute.id;
    const reason = (reasonById[id] ?? "").trim();
    if (reason === "") {
      setNotice("A decision needs a stated reason.");
      return;
    }
    setBusy(id);
    setNotice("");
    try {
      const res = await fetch(`/api/admin/review/disputes/${id}/${decision}`, {
        method: "POST",
        credentials: "same-origin",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ reason }),
      });
      if (!res.ok) {
        const body = (await res.json().catch(() => null)) as { error?: string } | null;
        // Verbatim, like the findings queue. The refusals name the actual
        // problem — "never the motive", "already upheld".
        setNotice(body?.error ?? "The decision could not be recorded.");
        return;
      }
      setNotice(
        decision === "uphold"
          ? "Upheld, and recorded in the correction log. Nothing has changed on the record — use “Correct the record, quoting this dispute” to make the change, and the log will join the two."
          : "Declined, and recorded in the correction log. The record stands.",
      );
      setReasonById((current) => ({ ...current, [id]: "" }));
      applyResult(await fetchDisputes());
    } catch {
      setNotice("The decision could not be sent.");
    } finally {
      setBusy("");
    }
  }

  const items = listing?.data ?? [];

  return (
    <div>
      <p className="mt-6 max-w-prose text-sm leading-relaxed text-ink-soft">
        A dispute is not a finding. It is somebody&rsquo;s contest of a record we
        published, filed through the public route, and it is never published
        itself.{" "}
        <strong className="font-semibold text-ink">
          Upholding one changes nothing on the record
        </strong>{" "}
        — it records that the contest looks right. Correcting the record is a
        separate act from its own page, with its own reason. The link below
        carries this dispute onto that page, and{" "}
        <code>record_corrections.dispute_id</code> is what ties the two together
        in the log and on the public corrections page.
      </p>

      {listing && (
        <dl className="mt-6 grid gap-4 sm:grid-cols-3">
          <div>
            <dt className="label-sm">Awaiting review</dt>
            <dd
              data-testid="disputes-received"
              className={`mt-1 figure text-lg ${
                listing.counts.received > 0 ? "text-accent" : "text-ink"
              }`}
            >
              {listing.counts.received}
            </dd>
          </div>
          <div>
            <dt className="label-sm">Upheld</dt>
            <dd className="mt-1 figure text-lg text-ink">{listing.counts.upheld}</dd>
          </div>
          <div>
            <dt className="label-sm">Declined</dt>
            <dd className="mt-1 figure text-lg text-ink">{listing.counts.declined}</dd>
          </div>
        </dl>
      )}

      <div className="mt-6 flex flex-wrap gap-2">
        {STATUSES.map((option) => (
          <button
            key={option}
            type="button"
            onClick={() => {
              setLoading(true);
              setStatus(option);
            }}
            aria-pressed={status === option}
            className={`${
              status === option ? buttonClass : secondaryButtonClass
            } ${focusRing}`}
          >
            {STATUS_LABEL[option]}
          </button>
        ))}
      </div>

      {error && (
        <p
          role="alert"
          className="mt-6 border-l-2 border-accent bg-paper px-4 py-3 text-sm text-ink-soft"
        >
          {error}
        </p>
      )}

      {notice && (
        <p
          role="status"
          className="mt-6 border-l-2 border-ink bg-paper px-4 py-3 text-sm text-ink-soft"
        >
          {notice}
        </p>
      )}

      {loading ? (
        <p className="mt-8 label-sm" role="status">
          Loading disputes…
        </p>
      ) : items.length === 0 ? (
        <PressroomCard className="mt-8">
          <p className="text-sm text-muted">{EMPTY_LABEL[status]}</p>
        </PressroomCard>
      ) : (
        <div className="mt-8 space-y-6">
          {items.map((item) => {
            const { dispute, context } = item;
            const pending = dispute.status === "received";
            return (
              <PressroomCard key={dispute.id}>
                <div className="flex flex-wrap items-baseline gap-3">
                  <span className="figure text-sm text-accent">{dispute.reference}</span>
                  <span className="label-sm">Dispute</span>
                  <span className="label-sm">{STATUS_LABEL[dispute.status]}</span>
                  <span className="label-sm tabular">{formatStamp(dispute.created_at)}</span>
                </div>

                <p className="mt-3 label-sm">{context.record_summary}</p>
                {context.commission_name && (
                  <p className="mt-1 text-sm text-muted">
                    {context.commission_name}
                    {context.jurisdiction_name ? ` · ${context.jurisdiction_name}` : ""}
                  </p>
                )}
                {context.meeting_id && (
                  <p className="mt-2 flex flex-wrap gap-x-4 gap-y-1">
                    <Link className="cite" to={`/admin/meetings/${context.meeting_id}`}>
                      Open the record
                    </Link>
                    {/* Carries the dispute through rather than asking the
                        operator to retype a reference. The correction screen
                        resolves the id, shows what it resolved to, and puts it
                        in `record_corrections.dispute_id` — which is the only
                        thing that makes dispute → decision → correction
                        followable in the log and on the public page. */}
                    <Link
                      className="cite"
                      data-testid={`correct-from-dispute-${dispute.id}`}
                      to={`/admin/meetings/${context.meeting_id}?dispute=${dispute.id}#record-a-correction`}
                    >
                      Correct the record, quoting this dispute
                    </Link>
                  </p>
                )}

                <div className="mt-5 border-l-2 border-rule pl-4">
                  <p className="label-sm">What is contested</p>
                  <p className="mt-1 max-w-prose text-sm leading-relaxed text-ink">
                    {dispute.contested}
                  </p>
                  <p className="label-sm mt-4">Their account, in their words</p>
                  <p className="mt-1 max-w-prose whitespace-pre-wrap text-sm leading-relaxed text-ink-soft">
                    {dispute.account}
                  </p>
                  <p className="label-sm mt-4">Contact</p>
                  <p className="mt-1 text-sm text-ink-soft">{dispute.contact}</p>
                </div>

                {pending ? (
                  <div className="mt-6">
                    <label htmlFor={`dispute-reason-${dispute.id}`} className="label-sm">
                      Your reason
                    </label>
                    <textarea
                      id={`dispute-reason-${dispute.id}`}
                      rows={3}
                      value={reasonById[dispute.id] ?? ""}
                      onChange={(event) =>
                        setReasonById((current) => ({
                          ...current,
                          [dispute.id]: event.target.value,
                        }))
                      }
                      className={`${fieldClass} ${focusRing}`}
                    />
                    <p className="mt-1.5 text-xs text-muted">
                      Describe the record, never the motive. This is appended to
                      the correction log and cannot be edited afterwards.
                    </p>

                    <div className="mt-4 flex flex-wrap gap-3">
                      <button
                        type="button"
                        disabled={busy === dispute.id}
                        onClick={() => void decide(item, "uphold")}
                        className={`${buttonClass} ${focusRing}`}
                      >
                        Uphold
                      </button>
                      <button
                        type="button"
                        disabled={busy === dispute.id}
                        onClick={() => void decide(item, "decline")}
                        className={`${secondaryButtonClass} ${focusRing}`}
                      >
                        Decline
                      </button>
                    </div>
                  </div>
                ) : (
                  <div className="mt-6 border-t border-rule pt-4">
                    <p className="label-sm">
                      {STATUS_LABEL[dispute.status]} · {formatStamp(dispute.reviewed_at)}
                      {dispute.reviewer_email ? ` · ${dispute.reviewer_email}` : ""}
                    </p>
                    <p className="mt-1 max-w-prose text-sm leading-relaxed text-ink-soft">
                      {dispute.review_reason}
                    </p>
                  </div>
                )}
              </PressroomCard>
            );
          })}
        </div>
      )}
    </div>
  );
}
